### PR TITLE
Add support for Facebook JSX

### PR DESCRIPTION
**Pull request by epeli**
https://facebook.github.io/jsx/

Works with pangloss/vim-javascript and mxw/vim-jsx

https://github.com/pangloss/vim-javascript
https://github.com/mxw/vim-jsx

### CODE REVIEW

**Comment by chollier** [comment]
I'm not sure this is the expected behavior.
JSX is usually compiled to javascript, I would expect tcomment to behave the same as a javascript wouldn't you ?

**Comment by tomtom** [comment]
Does commit 8955e2e improve the situation, given that &filetype = "javascript.jsx"?

**Comment by epeli** [comment]
What would be the expected behavior? Plain javascript comment inside JSX is a visible string. Not a comment.

This JSX

```
<div>
/* comment */
</div>
```

compiles to

```js
React.createElement(
  "div",
  null,
  "/* comment */"
);
```

and

```
<div>
{/* comment */}
</div>
```

compiles to

```js
React.createElement("div", null);
/* comment */
```

which is what at least I would expect.

**Comment by tomtom** [comment]
> |<div> {/* comment */} </div>|
That's how it works now, doesn't it -- when using the plugins the OP 
proposed and when filetype = "javascript.jsx".

**Pull request merged**
